/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cp.stackandqueue;

public class Stack {
    public static void main(String []args) {
    	System.out.println("Welcome to stack");
    }
}
