/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cp.stackandqueue;

import org.junit.Test;

import com.cp.stackandqueue.Stack;

import static org.junit.Assert.*;

public class StackTest {
 
}
